# Generated by Django 2.2 on 2020-08-13 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200810_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=2000, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Описание'),
        ),
    ]
