# Generated by Django 2.2 on 2020-08-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_article_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Описание')),
                ('newdate_at', models.DateField(max_length=10, null=True, verbose_name='Дата создания')),
                ('enddate_at', models.DateField(max_length=10, null=True, verbose_name='Дата выполнения')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.Article', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
