# Generated by Django 2.2 on 2020-08-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='Описание'),
        ),
    ]
